services:
  cybersec_classifier:
    image: ghcr.io/taranis-ai/taranis-cybersec-classifier:latest
    environment:
      DEBUG: "${DEBUG:-False}"
      MODEL: "${MODEL:-cybersec_mlp}"          
      API_KEY: "${API_KEY:-testkey}"            
    ports:
      - "${BOT_PORT:-5500}:8000"  
    restart: unless-stopped
