name: Build and merge images

on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  id-token: write
  attestations: write

jobs:
  build_container:
    name: Build and Push Containers
    strategy:
      fail-fast: false
      matrix:
        model: [bart_mnli, cybersec_mlp]

        os: [ubuntu-latest, ubuntu-24.04-arm]
    uses: taranis-ai/github-actions/.github/workflows/build-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-cybersec-classifier
      model: ${{ matrix.model }}
      os: ${{ matrix.os }}

  merge_container:
    name: Merge Container Manifests
    needs: build_container
    strategy:
      fail-fast: false
      matrix:
        model: [bart_mnli, cybersec_mlp]

    uses: taranis-ai/github-actions/.github/workflows/merge-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-cybersec-classifier
      model: ${{ matrix.model }}
      latest: ${{ matrix.model == 'cybersec_mlp' }}

